In [3]:
from transformers import GPT2LMHeadModel,GPT2Tokenizer

In [5]:
model = GPT2LMHeadModel.from_pretrained('gpt2')

c:\Users\dsd09\anaconda3\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


In [9]:
model.parameters

<bound method Module.parameters of GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0): GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D()
          (c_proj): Conv1D()
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D()
          (c_proj): Conv1D()
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
      (1): GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D()
          (c_proj): Conv1D()
          (attn_dropout): Dropout(p=0.1, inplace=Fa

In [29]:
model.transformer.h[0].attn

GPT2Attention(
  (c_attn): Conv1D()
  (c_proj): Conv1D()
  (attn_dropout): Dropout(p=0.1, inplace=False)
  (resid_dropout): Dropout(p=0.1, inplace=False)
)

In [25]:
model.transformer.h[0].attn.c_attn.weight.size()

torch.Size([768, 2304])

In [38]:
from transformers import GPT2LMHeadModel

In [216]:
model = GPT2LMHeadModel.from_pretrained('gpt2',output_attentions=True)

c:\Users\dsd09\anaconda3\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


In [16]:
from transformers import GPT2LMHeadModel,GPT2Tokenizer

# GPT-2 모델을 output_attentions=True로 설정하여 로드
model = GPT2LMHeadModel.from_pretrained('gpt2', output_attentions=True)
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')

# 입력 텍스트
input_ids = tokenizer.encode("Hello, how are you?", return_tensors="pt")

# 모델을 통해 입력을 전달하여 출력과 어텐션 가중치 받기
outputs = model(input_ids)

# 출력 중 어텐션 가중치를 추출
attentions = outputs.attentions

# 각 레이어의 어텐션 가중치 출력
for layer, attention in enumerate(attentions):
    print(f"Layer {layer + 1} attention shape: {attention.shape}")


tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Layer 1 attention shape: torch.Size([1, 12, 6, 6])
Layer 2 attention shape: torch.Size([1, 12, 6, 6])
Layer 3 attention shape: torch.Size([1, 12, 6, 6])
Layer 4 attention shape: torch.Size([1, 12, 6, 6])
Layer 5 attention shape: torch.Size([1, 12, 6, 6])
Layer 6 attention shape: torch.Size([1, 12, 6, 6])
Layer 7 attention shape: torch.Size([1, 12, 6, 6])
Layer 8 attention shape: torch.Size([1, 12, 6, 6])
Layer 9 attention shape: torch.Size([1, 12, 6, 6])
Layer 10 attention shape: torch.Size([1, 12, 6, 6])
Layer 11 attention shape: torch.Size([1, 12, 6, 6])
Layer 12 attention shape: torch.Size([1, 12, 6, 6])


In [14]:
import winogender

In [17]:
examples = winogender.load_examples()
interventions = [ex.to_intervention(tokenizer, 'bls') for ex in examples]
x = interventions[0].base_strings_tok[0]
x_alt = interventions[0].base_strings_tok[1]
print(f"base_string:{x}")
print(f"alt_strings:{x_alt}")

Keyword arguments {'add_space_before_punct_symbol': True} not recognized.
Keyword arguments {'add_space_before_punct_symbol': True} not recognized.
Keyword arguments {'add_space_before_punct_symbol': True} not recognized.
Keyword arguments {'add_space_before_punct_symbol': True} not recognized.
Keyword arguments {'add_space_before_punct_symbol': True} not recognized.
Keyword arguments {'add_space_before_punct_symbol': True} not recognized.
Keyword arguments {'add_space_before_punct_symbol': True} not recognized.
Keyword arguments {'add_space_before_punct_symbol': True} not recognized.
Keyword arguments {'add_space_before_punct_symbol': True} not recognized.
Keyword arguments {'add_space_before_punct_symbol': True} not recognized.
Keyword arguments {'add_space_before_punct_symbol': True} not recognized.
Keyword arguments {'add_space_before_punct_symbol': True} not recognized.
Keyword arguments {'add_space_before_punct_symbol': True} not recognized.
Keyword arguments {'add_space_before_p

base_string:tensor([  464, 33024,  1297,   262,  6491,   326,   673])
alt_strings:tensor([  464, 33024,  1297,   262,  6491,   326,   339])


In [92]:
print(tokenizer.convert_ids_to_tokens(x))
print(tokenizer.convert_ids_to_tokens(x_alt))

['The', 'Ġtechnician', 'Ġtold', 'Ġthe', 'Ġcustomer', 'Ġthat', 'Ġshe']
['The', 'Ġtechnician', 'Ġtold', 'Ġthe', 'Ġcustomer', 'Ġthat', 'Ġhe']


In [105]:
logits = model(x_alt).logits

In [106]:
import torch
import torch.nn.functional as F

In [118]:
# 마지막 토큰에 대한 로짓을 선택
last_token_logits = logits[-1,:]

# 소프트맥스 함수로 확률 계산
probabilities = F.softmax(last_token_logits, dim=-1)

# 가장 높은 확률을 가진 토큰 선택
predicted_token_id = torch.argmax(probabilities).item()
predicted_token = tokenizer.decode([predicted_token_id])

print(f"Predicted next token: {predicted_token}")

Predicted next token:  had


In [113]:
last_token_logits

tensor([ -41.3759, -126.2039,  -89.6250, -102.7298,  -97.1775, -102.6191,
        -136.7418], grad_fn=<SelectBackward0>)

In [114]:
predicted_token_id

0

In [121]:
len(model(x)[-1])

12

In [124]:
tokenizer.decode(interventions[0].candidates_tok[0])

' could pay with cash.'

In [125]:
tokenizer.decode(interventions[0].candidates_tok[1])

' had completed the repair.'

In [130]:
x.tolist()

[464, 33024, 1297, 262, 6491, 326, 673]

In [133]:
x_prime = x.tolist()
batch = x_prime + interventions[0].candidates_tok[0]

In [144]:
len(batch)

12

In [134]:
batch_prime = torch.tensor(batch[:-1]).unsqueeze(dim=0)
batch_prime

tensor([[  464, 33024,  1297,   262,  6491,   326,   673,   714,  1414,   351,
          5003]])

In [140]:
logits = model(batch_prime)[0]
logits.size()

torch.Size([1, 11, 50257])

In [142]:
log_logits = F.log_softmax(logits[-1,:,:],dim=-1)
log_logits.size()

torch.Size([11, 50257])

In [207]:
x.size()

torch.Size([7])

In [218]:
output = model(x.clone().detach().unsqueeze(0))
attn = output.attentions
len(attn)

12

In [224]:
attn[0][0][1].size()

torch.Size([7, 7])

In [194]:
x.clone().detach().unsqueeze(0)

tensor([[  464, 33024,  1297,   262,  6491,   326,   673]])

In [199]:
model.config.num_attention_heads

12

In [201]:
model.config

GPT2Config {
  "_name_or_path": "gpt2",
  "activation_function": "gelu_new",
  "architectures": [
    "GPT2LMHeadModel"
  ],
  "attn_pdrop": 0.1,
  "bos_token_id": 50256,
  "embd_pdrop": 0.1,
  "eos_token_id": 50256,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_inner": null,
  "n_layer": 12,
  "n_positions": 1024,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "task_specific_params": {
    "text-generation": {
      "do_sample": true,
      "max_length": 50
    }
  },
  "transformers_version": "4.37.2",
  "use_cache": true,
  "vocab_size": 50257
}

In [1]:
import torch

In [4]:
condition = torch.ones([1,3],dtype=bool)
A = torch.zeros([1,3])
A = torch.where(condition,2,0)

In [5]:
A

tensor([[2, 2, 2]])

In [6]:
from transformers import GPT2LMHeadModel,GPT2Tokenizer


In [66]:
model = GPT2LMHeadModel.from_pretrained('gpt2',output_attentions=True)

In [35]:
token_embed = model.transformer.wte(x)
model.transformer.h[0].attn.c_attn(token_embed).size()

torch.Size([7, 2304])

In [40]:
tmp_x = model.transformer.h[0].attn.c_attn(token_embed)

In [43]:
tmp_x.size()

torch.Size([7, 2304])

In [45]:
q,k,v = tmp_x.split(3,dim=0)
print(q.size())
print(k.size())
print(v.size())


torch.Size([3, 2304])
torch.Size([3, 2304])
torch.Size([1, 2304])


In [46]:
q,k,v = tmp_x.chunk(3,dim=0)
print(q.size())
print(k.size())
print(v.size())

torch.Size([3, 2304])
torch.Size([3, 2304])
torch.Size([1, 2304])


In [103]:
attention_layer = lambda layer: model.transformer.h[layer].attn
attention_layer(1)

GPT2Attention(
  (c_attn): Conv1D()
  (c_proj): Conv1D()
  (attn_dropout): Dropout(p=0.1, inplace=False)
  (resid_dropout): Dropout(p=0.1, inplace=False)
)

In [126]:
attention_layer(1)._buffers

OrderedDict([('bias',
              tensor([[[[ True, False, False,  ..., False, False, False],
                        [ True,  True, False,  ..., False, False, False],
                        [ True,  True,  True,  ..., False, False, False],
                        ...,
                        [ True,  True,  True,  ...,  True, False, False],
                        [ True,  True,  True,  ...,  True,  True, False],
                        [ True,  True,  True,  ...,  True,  True,  True]]]])),
             ('masked_bias', tensor(-10000.))])

In [121]:
new_shape = tmp_x.size()[:-1] + (12,tmp_x.size(-1)//attention_layer(1).num_heads)
tmp_x.view(*new_shape).size()

torch.Size([7, 12, 192])

In [116]:
tmp_x.size()

torch.Size([7, 2304])

In [122]:
model.transformer.h[0].attn.c_attn.weight.size()

torch.Size([768, 2304])

In [127]:
import torch
import torch.nn as nn

class Model(nn.Module):
	def __init__(self):
		super().__init__()
		
		self.param = nn.Parameter(torch.randn([2, 2]))
		
		buff = torch.randn([2, 2])
		self.register_buffer('buff', buff)

		self.non_buff = torch.randn([2, 2])

	def forward(self, x):
		return x

model = Model()
print(model.state_dict())

OrderedDict([('param', tensor([[0.6614, 0.2669],
        [0.0617, 0.6213]])), ('buff', tensor([[-0.4519, -0.1661],
        [-1.5228,  0.3817]]))])


In [128]:
1e4

10000.0